#!name=腾讯体育去广告
#!desc=拦截开屏广告，移除首页信息流、会员推广、赛事页及悬浮推广组件

[rewrite_local]
^https:\/\/config\.ab\.qq\.com\/tab\/GetTabRemoteConfig.* url reject-200
^https:\/\/config\.ab\.qq\.com\/tab\/GetTabToggle.* url reject-200

^https:\/\/(?:app\.sports\.qq\.com\/(?:feeds\/list|m\/matchAfter\/stats|match\/adBanner)\?|shequ\.sports\.qq\.com\/topic\/detail\?|film\.video\.qq\.com\/x\/sports-vip-channel\/(?:\?.*)?$) url script-response-body https://raw.githubusercontent.com/Hey-sayiwanna/TencentSports-Surge/main/TencentSportsAdBlock.js

^https:\/\/(?:app\.sports\.qq\.com\/(?:trpc\.sports_resource\.cgi\.ResourceCGI\/MatchWidgets|vaccess\/trpc\.sports_resource\.cgi\.ResourceCGI\/ColumnWidget|user\/homePageV2)|sports\.qq\.com\/sapp\/h5msg\.htm)(?:\?.*)?$ url script-response-body https://raw.githubusercontent.com/Hey-sayiwanna/TencentSports-Surge/main/TencentSportsFloatBlock.js

[mitm]
hostname = %APPEND%, app.sports.qq.com, config.ab.qq.com, shequ.sports.qq.com, film.video.qq.com, sports.qq.com
